### ISSUE TITLE
Readme 中的链接失效了

### ISSUE THREAD

**Issue by feichao93** [moeoverflow/animeloop-cli#2]
返回 404 了

![image](https://user-images.githubusercontent.com/5550931/38775509-245d58e4-40b7-11e8-8c4e-39ab545355af.png)

**Comment by shincurry** [comment]
fixed.

**Comment by NotRealPaz** [comment]
@shincurry It's still 404

**Comment by shincurry** [comment]
👌🏻fixed.again.
