### ISSUE TITLE
Add pre-built binaries

### ISSUE THREAD

**Issue by ZenaMel** [moeoverflow/animeloop-cli#6]
Adding binaries that allow users to run the software out-of-the-box would make the project more accessible. The steps needed to just use the CLI on Windows are a lot.

**Comment by shincurry** [comment]
animeloop-cli is an experimental project, this cli tool is not widely used, so I don’t think it is necessary to publish pre-built binaries.

**Comment by ZenaMel** [comment]
Agreed that it wouldn't be neccessary but it would be nice. Closing this issue.
